---
kind: pipeline
name: build-pkg

clone:
  depth: 200

volumes:
- name: distdir
  host:
    path: /srv/dist/dist
- name: keysdir
  host:
    path: /var/keys
- name: cache
  host:
    path: /var/cache/drone

steps:
- name: extract-cache
  image: drillster/drone-volume-cache
  pull: always
  volumes:
  - name: cache
    path: /cache
  settings:
    mount:
    - hostdir
    restore: true

- name: prepare-build
  image: cogitri/voidlinux-ci
  pull: always
  commands:
  - common/drone/prepare.sh
  - common/drone/bootstrap.sh

- name: do-build
  image: cogitri/voidlinux-ci
  privileged: true
  environment:
    XBPS_MAKEJOBS: 6
    XBPS_ALLOW_RESTRICTED: yes
    XBPS_DEBUG_PKGS: yes
  commands:
  - common/drone/changed_templates.sh
  - common/drone/build.sh x86_64 x86_64

- name: do-deploy
  image: cogitri/voidlinux-ci
  volumes:
  - name: distdir
    path: /dist
  - name: keysdir
    path: /keys
  environment:
    SIGN_PW:
      from_secret: pkg_sign_pw
  commands:
  - cp -r hostdir/binpkgs/systemd/* /dist
  - /keys/sign-pkgs

- name: create-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    mount:
    - hostdir
    rebuild: true

trigger:
  branch:
  - systemd
---
kind: signature
hmac: ad6b1f3285429e759043daaa434d2a47f358b34793410e201a64c3f5137ac466

...
