---
kind: pipeline
name: build-pkg

clone:
  depth: 200

volumes:
- name: distdir
  host:
    path: /srv/dist/dist
- name: keysdir
  host:
    path: /var/keys
- name: cache
  host:
    path: /var/cache/drone

steps:
- name: prepare-build
  image: cogitri/voidlinux-ci
  pull: always
  commands:
  - common/drone/prepare.sh
  - common/drone/bootstrap.sh

- name: do-build
  image: cogitri/voidlinux-ci
  privileged: true
  environment:
    XBPS_MAKEJOBS: 6
    XBPS_ALLOW_RESTRICTED: yes
    XBPS_DEBUG_PKGS: yes
  commands:
  - common/drone/changed_templates.sh
  - common/drone/build.sh x86_64 x86_64

- name: do-deploy
  image: cogitri/voidlinux-ci
  volumes:
  - name: distdir
    path: /dist
  - name: keysdir
    path: /keys
  environment:
    SIGN_PW:
      from_secret: pkg_sign_pw
  commands:
  - cp -r hostdir/binpkgs/systemd/*.xbps /dist
  - /bin/bash $(cp -r hostdir/binpkgs/systemd/debug/*.xbps /dist/debug || :)
  - /keys/sign-pkgs

- name: matrix-notification
  image: plugins/matrix
  settings:
    roomid: pRVxCrDHTiIdkIxFtr:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
     - success
     - failure

trigger:
  branch:
  - systemd
---
kind: signature
hmac: 5fb2804006f1a101d92bad0733918eb84162cec00bc9aad1ea34c32681322102

...
